# .github/workflows/daily_debug.yml
name: Daily OS Scraper Debug

on:
  schedule:
    - cron: "0 22 * * *" # 8 AM AEST -> 10 PM UTC previous day
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run scraper (debug)
        run: python main.py
